import { Metadata } from 'next'
import Header from '@/components/landing/Header'

export const metadata: Metadata = {
  title: 'Terms of Service - PXV Pay',
  description: 'Terms of Service for PXV Pay platform and services.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-black">
      <Header />
      
      <main className="pt-32 pb-16">
        <div className="container mx-auto px-6 max-w-4xl">
          {/* Header */}
          <div className="mb-12 text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-black dark:text-white mb-4">
              Terms of Service
            </h1>
            <p className="text-lg text-gray-600 dark:text-gray-400">
              Last Updated: June 3, 2025
            </p>
          </div>

          {/* Content */}
          <div className="prose prose-lg max-w-none dark:prose-invert">
            <div className="bg-gray-50 dark:bg-gray-900 p-6 rounded-lg mb-8">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                Please read these Terms of Service ("Terms") carefully before using the PXV Pay website and services operated by PRIMEX VANGUARD ("us," "we," or "our").
              </p>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
                By accessing or using the PXV Pay platform, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
              </p>
            </div>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">1. Definitions</h2>
              <div className="space-y-4 text-gray-700 dark:text-gray-300">
                <p><strong>PXV Pay Platform/Service:</strong> Refers to the website, mobile applications (if applicable), and all services provided by PXV Pay, including payment link generation, checkout flow, and merchant administration tools.</p>
                <p><strong>User:</strong> Refers to any individual accessing or using the PXV Pay Platform.</p>
                <p><strong>Merchant:</strong> A registered User who utilizes the PXV Pay Platform to generate payment links and collect payments from their Customers.</p>
                <p><strong>Customer:</strong> An individual who makes a payment to a Merchant using the PXV Pay Platform's checkout flow.</p>
                <p><strong>Payment Link:</strong> A unique URL generated by a Merchant on the PXV Pay Platform, which directs a Customer to a PXV Pay checkout page.</p>
                <p><strong>Payment Method:</strong> A method of payment configured by a Merchant on the PXV Pay Platform (e.g., bank transfer, mobile money, or future integrated methods).</p>
                <p><strong>Payment Proof:</strong> A document or image uploaded by a Customer to confirm a manual payment.</p>
                <p><strong>Content:</strong> Any text, images, data, or other information uploaded, posted, or displayed on the PXV Pay Platform by Users or PXV Pay.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">2. PXV Pay's Role (Crucial Clarification)</h2>
              <div className="bg-violet-50 dark:bg-violet-950/20 p-6 rounded-lg space-y-4 text-gray-700 dark:text-gray-300">
                <p><strong>PXV Pay is a Payment Information Facilitator and Platform Provider.</strong> We are NOT a payment processor, bank, financial institution, or money transmitter.</p>
                <p>PXV Pay does not hold, receive, or transfer any funds. We provide the tools for Merchants to generate payment links, display payment instructions, and collect payment proofs.</p>
                <p>PXV Pay does not guarantee or process payments. The actual transfer of funds occurs directly between the Customer and the Merchant via the Payment Method chosen by the Customer (e.g., direct bank transfer, mobile money transfer).</p>
                <p>PXV Pay is not responsible for the underlying financial transaction. Merchants are solely responsible for ensuring they receive actual funds, verifying Payment Proofs, and complying with all laws and regulations related to their business and payment collection.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">3. Account Creation and Eligibility</h2>
              <div className="space-y-4 text-gray-700 dark:text-gray-300">
                <p><strong>Eligibility:</strong> You must be at least 18 years old and have the legal capacity to enter into these Terms. By creating an account, you represent and warrant that you meet these requirements.</p>
                <p><strong>Account Information:</strong> You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.</p>
                <p><strong>Account Security:</strong> You are responsible for safeguarding your password and for any activities or actions under your account. You agree not to disclose your password to any third party. PXV Pay cannot and will not be liable for any loss or damage arising from your failure to maintain the security of your account and password.</p>
                <p><strong>Roles:</strong> Upon registration, you will be assigned a "Registered User" role. Your access and permissions will be determined by your role (e.g., Registered User, Subscriber, Free User, Super Admin) as defined by PXV Pay.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">4. Use of the Service</h2>
              <div className="space-y-4 text-gray-700 dark:text-gray-300">
                <h3 className="text-xl font-semibold text-black dark:text-white">Merchant Responsibilities:</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>You are solely responsible for the products, services, or activities for which you collect payments using the PXV Pay Platform.</li>
                  <li>You must ensure that your use of PXV Pay complies with all applicable laws, regulations, and industry standards in your jurisdiction and the jurisdictions of your Customers.</li>
                  <li>You are responsible for verifying Payment Proofs and confirming actual receipt of funds from your Customers.</li>
                  <li>You must clearly communicate your own terms of sale, refund policies, and customer service procedures directly to your Customers.</li>
                  <li>You must not use PXV Pay for any illegal, fraudulent, or unauthorized activities.</li>
                </ul>

                <h3 className="text-xl font-semibold text-black dark:text-white mt-6">Prohibited Activities:</h3>
                <p>You agree not to engage in any of the following prohibited activities:</p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Using the Service for any illegal or unauthorized purpose.</li>
                  <li>Interfering with or disrupting the integrity or performance of the Service.</li>
                  <li>Attempting to gain unauthorized access to the Service or its related systems or networks.</li>
                  <li>Uploading or transmitting any viruses, worms, or other malicious code.</li>
                  <li>Collecting or harvesting any personally identifiable information from the Service without proper consent.</li>
                  <li>Impersonating any person or entity, or falsely stating or otherwise misrepresenting your affiliation with a person or entity.</li>
                  <li>Using the Service to collect payments for products, services, or activities that violate any applicable laws, regulations, or PXV Pay's acceptable use policies (which may be updated from time to time). This includes, but is not limited to, illegal drugs, weapons, child exploitation, terrorism, or other highly regulated or illegal activities.</li>
                </ul>

                <p><strong>Payment Links & Checkout Flow:</strong> PXV Pay provides tools to generate Payment Links. The appearance and functionality of the checkout page will be determined by your configurations and PXV Pay's platform design.</p>
                <p><strong>Custom Landing Pages (Subscriber Feature):</strong> If available and you are a Subscriber, you may create custom landing pages. You are responsible for ensuring all content on your custom landing page complies with these Terms and all applicable laws. PXV Pay reserves the right to remove any content or landing page that violates these Terms.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">5. Intellectual Property</h2>
              <div className="space-y-4 text-gray-700 dark:text-gray-300">
                <p><strong>PXV Pay Content:</strong> The Service and its original content (excluding Content provided by Users), features, and functionality are and will remain the exclusive property of PRIMEX VANGUARD/PXV Pay and its licensors. The Service is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of PRIMEX VANGUARD/PXV Pay.</p>
                <p><strong>User Content:</strong> You retain all rights in, and are solely responsible for, the Content you upload, post, or display on or through the Service. By posting Content on or through the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service solely for the purpose of operating and providing the Service.</p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">6. Disclaimers</h2>
              <div className="bg-gray-50 dark:bg-gray-900 p-6 rounded-lg">
                <p className="text-gray-700 dark:text-gray-300 uppercase font-semibold">
                  THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. PXV PAY MAKES NO WARRANTIES, EXPRESSED OR IMPLIED, AND HEREBY DISCLAIMS AND NEGATES ALL OTHER WARRANTIES, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER VIOLATION OF RIGHTS. FURTHER, PXV PAY DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS CONCERNING THE ACCURACY, LIKELY RESULTS, OR RELIABILITY OF THE USE OF THE MATERIALS ON ITS WEBSITE OR OTHERWISE RELATING TO SUCH MATERIALS OR ON ANY SITES LINKED TO THIS SITE.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">7. Limitation of Liability</h2>
              <div className="bg-gray-50 dark:bg-gray-900 p-6 rounded-lg">
                <p className="text-gray-700 dark:text-gray-300 uppercase font-semibold">
                  IN NO EVENT SHALL PXV PAY, NOR ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; (III) ANY CONTENT OBTAINED FROM THE SERVICE; AND (IV) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">8. Indemnification</h2>
              <p className="text-gray-700 dark:text-gray-300">
                You agree to defend, indemnify and hold harmless PXV Pay and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms; or c) your violation of any laws or regulations, including those related to payment collection or your business activities.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">9. Termination</h2>
              <p className="text-gray-700 dark:text-gray-300">
                We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or contact us.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">10. Governing Law and Dispute Resolution</h2>
              <p className="text-gray-700 dark:text-gray-300">
                These Terms shall be governed and construed in accordance with applicable laws, without regard to conflict of law provisions. Any dispute arising from or relating to the subject matter of these Terms shall be subject to the exclusive jurisdiction of the appropriate courts.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">11. Changes to These Terms</h2>
              <p className="text-gray-700 dark:text-gray-300">
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-black dark:text-white mb-4">12. Contact Us</h2>
              <div className="bg-violet-50 dark:bg-violet-950/20 p-6 rounded-lg">
                <p className="text-gray-700 dark:text-gray-300 mb-4">
                  If you have any questions about these Terms, please contact us:
                </p>
                <div className="space-y-2 text-gray-700 dark:text-gray-300">
                  <p>By email: <a href="mailto:contact@primexvanguard.com" className="text-violet-600 dark:text-violet-400 hover:underline">contact@primexvanguard.com</a></p>
                  <p>By visiting our contact page on our website</p>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
} 